[general]
import = ["~/.config/alacritty/themes/noctalia.toml"]

[window]
padding = { x = 15, y = 15 }
decorations = "None"
opacity = 0.9

[font]
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
size = 11.5
